#ifndef DRONECONTROL_H
#define DRONECONTROL_H 
#include <iostream>
#include <thirdparty/eigenWrapper.h>
#include <vector>
#include <controlRequestStructs.h>
#include <util/util.h>
#include <fc_units.h>
#include <spdlog/spdlog.h>

using namespace Eigen;
using namespace std;
namespace avionics{

struct allocatorData{
    std::vector<units::scalar> thrusts;
    fc_units::vec3 forces;
    fc_units::vec3 moments; 

    inline void printAllocatorData(const std::shared_ptr<spdlog::logger>& logger) {
        SPDLOG_LOGGER_INFO(logger, "Allocator Data:");

        std::ostringstream thrusts_ss;
        thrusts_ss << "[";
        for (size_t i = 0; i < thrusts.size(); ++i) {
            thrusts_ss << thrusts[i];
            if (i < thrusts.size() - 1) thrusts_ss << ", ";
        }
        thrusts_ss << "]";
        
        SPDLOG_LOGGER_INFO(logger, "  Thrusts: {}", thrusts_ss.str());

        SPDLOG_LOGGER_INFO(logger, "  Forces:  [{}, {}, {}]",
            forces[0], forces[1], forces[2]);

        SPDLOG_LOGGER_INFO(logger, "  Moments: [{}, {}, {}]",
            moments[0], moments[1], moments[2]);
    }
};



class controlAllocator {
private:
    vector<Vector3d> positions;   
    vector<Vector3d> thrustDirs;   
    VectorXd spinTorque;           
    MatrixXd B;         
    MatrixXd Bpinv;
    vector<utility::movingAverage<units::scalar>> movingAvg; 

    void buildCASMatrix();

    void manageMovingAvg(allocatorData& requestPacket);
public:

    controlAllocator(const vector<std::array<units::scalar,3>>& motorPositions,const vector<std::array<units::scalar,3>>& thrustDirections,vector<units::scalar> spinTCoefficient);
    controlAllocator(const controlAllocator& other) = default;
    /**
     * @brief Solves for the rotor thrusts required to produce the given wrench (force and torque).
     * @param desiredwrench 6D vector: [Fx, Fy, Fz, Tx, Ty, Tz]
     * @return Vector of individual motor thrusts
     */
    inline VectorXd allocate(const VectorXd& desiredwrench) const {
        VectorXd thrusts = Bpinv * desiredwrench;
        return thrusts;
    }


    inline const MatrixXd& getCASMatrix() const {
        return B;
    }

    /**
     * @brief Computes the actual force/torque (wrench) generated by a given vector of thrusts
     * @param thrusts Vector of individual motor thrusts
     * @return 6D vector: [Fx, Fy, Fz, Tx, Ty, Tz]
     */
    inline VectorXd computeWrench(const VectorXd& thrusts) const {
        return B * thrusts;
    }

    VectorXd toVectorXd(std::initializer_list<units::scalar> list);

    allocatorData computeAllocation(controlPacks::forceMoments requestPacket);

};


} //SimCore

#endif
