vehicle:
  wind: [0.0, 0.0, 0.0]
  gravitationalAcceleration: -9.8067	
  initPosition: [-10.0, -10.0, 10.0]
  initVehicleState: [0.0, 0.0, 1.0]
  MOI: [0.01, 0.01, 0.01]
  initVelocity: [0.0, 0.0, 0.0]
  centerOfPressure: 0.0
  cogToEngine: -8.0
  timeStep: 0.001
  mass: 0.3
  maxCruiseVelocity: 8.0

accelerometer:
  frequency: 1000.0
  NoisePowerSpectralDensity: 0.03
  bandwidth: 100.0
  bias: 0.0
  burst: true
  burstStdDeviation: 0.02
  maxBurstDuration: 0.5

GNSS:
  frequency: 10.0
  NoisePowerSpectralDensity: 0.02
  bandwidth: 100.0
  bias: 0.0
  burst: true
  burstStdDeviation: 0.01
  maxBurstDuration: 1.0
  lat_deg: 34.27264233926578
  long_deg: -118.45680680950842
  alt_m: 0.0
  velocityNoisePowerSpectralDensity: 0.01
  velocityBandwidth: 100.0
  velocityBias: 0.0

gyro:
  frequency: 10.0
  NoisePowerSpectralDensity: 3.0
  bandwidth: 100.0
  bias: 0.0
  burst: true
  burstStdDeviation: 0.5
  maxBurstDuration: 0.4

component_library:
  motor: "motor.toml"
  propeller: "propeller.toml"

actuator:
  - name: front_right
    position: [0.15, 0.15, 0.0]
    thrustDirection: [0.0, 0.0, 1.0]
    rotationDirection: -1

  - name: front_left
    position: [0.15, -0.15, 0.0]
    thrustDirection: [0.0, 0.0, 1.0]
    rotationDirection: 1

  - name: rear_left
    position: [-0.15, -0.15, 0.0]
    thrustDirection: [0.0, 0.0, 1.0]
    rotationDirection: -1

  - name: rear_right
    position: [-0.15, 0.15, 0.0]
    thrustDirection: [0.0, 0.0, 1.0]
    rotationDirection: 1